# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FoodieAppNew' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FoodieAppNew
 pod 'CBFlashyTabBarController'
 pod 'IQKeyboardManagerSwift'
  pod 'AMShimmer'
  pod 'NVActivityIndicatorView'
  pod 'Alamofire'
  pod 'ReachabilitySwift'
  pod 'AlamofireNetworkActivityLogger', '~> 2.0'
  pod 'MagicalRecord'
  pod 'FastEasyMapping', '~> 1.2'
  pod 'ActionSheetPicker-3.0'
  pod 'Kingfisher'

  
 
  target 'FoodieAppNewTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'FoodieAppNewUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
