# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Foodie' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  
  # Pods for Foodie
  pod 'IQKeyboardManagerSwift'
  
  pod 'Alamofire'
  pod 'ReachabilitySwift'
  pod 'AlamofireNetworkActivityLogger', '~> 2.0'
  pod 'MagicalRecord'
  pod 'FastEasyMapping', '~> 1.2'
  pod 'ActionSheetPicker-3.0'
  pod 'Kingfisher'
  #  pod 'ParallaxHeader'
  pod 'RSReusable'
  pod 'SnapKit'
  pod 'AMShimmer'
  pod 'WOWRibbonView'
  pod 'GoogleMaps'
  pod 'GooglePlaces'
  
  target 'FoodieTests' do
    inherit! :search_paths
    # Pods for testing
  end
  
  target 'FoodieUITests' do
    inherit! :search_paths
    # Pods for testing
  end
  
end
